-- SQLite. Una fila por cliente; importes exactos en centavos ademas del decimal.
PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS customers (
  customerID TEXT PRIMARY KEY NOT NULL,
  gender TEXT NOT NULL CHECK(gender IN ('Female','Male')),
  SeniorCitizen INTEGER NOT NULL CHECK(SeniorCitizen IN (0,1)),
  Partner TEXT NOT NULL CHECK(Partner IN ('Yes','No')),
  Dependents TEXT NOT NULL CHECK(Dependents IN ('Yes','No')),
  tenure INTEGER NOT NULL CHECK(tenure >= 0),
  PhoneService TEXT NOT NULL CHECK(PhoneService IN ('Yes','No')),
  MultipleLines TEXT NOT NULL CHECK(MultipleLines IN ('Yes','No','No phone service')),
  InternetService TEXT NOT NULL CHECK(InternetService IN ('DSL','Fiber optic','No')),
  OnlineSecurity TEXT NOT NULL CHECK(OnlineSecurity IN ('Yes','No','No internet service')),
  OnlineBackup TEXT NOT NULL CHECK(OnlineBackup IN ('Yes','No','No internet service')),
  DeviceProtection TEXT NOT NULL CHECK(DeviceProtection IN ('Yes','No','No internet service')),
  TechSupport TEXT NOT NULL CHECK(TechSupport IN ('Yes','No','No internet service')),
  StreamingTV TEXT NOT NULL CHECK(StreamingTV IN ('Yes','No','No internet service')),
  StreamingMovies TEXT NOT NULL CHECK(StreamingMovies IN ('Yes','No','No internet service')),
  Contract TEXT NOT NULL CHECK(Contract IN ('Month-to-month','One year','Two year')),
  PaperlessBilling TEXT NOT NULL CHECK(PaperlessBilling IN ('Yes','No')),
  PaymentMethod TEXT NOT NULL CHECK(PaymentMethod IN ('Electronic check','Mailed check','Bank transfer (automatic)','Credit card (automatic)')),
  MonthlyCharges REAL NOT NULL CHECK(MonthlyCharges >= 0),
  TotalCharges REAL CHECK(TotalCharges >= 0),
  Churn TEXT NOT NULL CHECK(Churn IN ('Yes','No')),
  ChurnFlag INTEGER NOT NULL CHECK(ChurnFlag IN (0,1)),
  MonthlyChargesCents INTEGER NOT NULL CHECK(MonthlyChargesCents >= 0),
  TotalChargesCents INTEGER CHECK(TotalChargesCents >= 0),
  TotalChargesMissing INTEGER NOT NULL CHECK(TotalChargesMissing IN (0,1)),
  TenureBand TEXT NOT NULL,
  TenureBandOrder INTEGER NOT NULL CHECK(TenureBandOrder BETWEEN 1 AND 5),
  ChargeBand TEXT NOT NULL,
  ChargeBandOrder INTEGER NOT NULL CHECK(ChargeBandOrder BETWEEN 1 AND 3),
  ServiceCount INTEGER NOT NULL CHECK(ServiceCount BETWEEN 0 AND 9),
  PaymentType TEXT NOT NULL CHECK(PaymentType IN ('Automatico','Manual')),
  SegmentID TEXT NOT NULL CHECK(SegmentID IN ('S1','S2','S3','S4','S5','S6')),
  ContractLabel TEXT NOT NULL,
  ContractOrder INTEGER NOT NULL,
  InternetLabel TEXT NOT NULL,
  SupportLabel TEXT NOT NULL,
  PaymentLabel TEXT NOT NULL,
  ChurnLabel TEXT NOT NULL,
  CHECK(ChurnFlag = CASE WHEN Churn = 'Yes' THEN 1 ELSE 0 END),
  CHECK(TotalChargesMissing = CASE WHEN TotalCharges IS NULL THEN 1 ELSE 0 END),
  CHECK((TotalCharges IS NULL) = (TotalChargesCents IS NULL))
);
CREATE INDEX IF NOT EXISTS idx_segment ON customers(SegmentID, ChurnFlag);
CREATE INDEX IF NOT EXISTS idx_contract_tenure ON customers(Contract, TenureBandOrder);
